name: 'Pact provider tests'
description: 'Run pact provider tests if pacts have changed'
inputs:
  pact-broker-url:
    description: URL of the pact broker
    required: true
  pact-broker-username:
    description: Pact broker username
    required: true
  pact-broker-password:
    description: Pact broker password
    required: true
  consumer:
    description: The pact consumer
    required: true
  consumer-tag: 
    description: The tag for consumer pact file to check for providers needing validation against
    required: true
outputs:
  providers-needing-validation:
    description: 'List of providers needing validation against consumer version'
runs:
  using: 'node12'
  main: 'dist/index.js'
